stages:
  - test
  - build
  - func_test
  - deploy


.pytest:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest --junitxml=junit.xml tests/unit_tests
  artifacts:
    reports:
      junit: junit.xml

.docker-registry-auth:
    before_script:
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

.build-docker-kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  extends: .docker-registry-auth
  script:
    - >-
      /kaniko/executor
      --context "${CONTEXT_PATH}"
      --dockerfile "${DOCKERFILE_PATH}"
      --cache-copy-layers
      --destination "${CI_REGISTRY_IMAGE}/$IMAGE_NAME:$IMAGE_TAG"
      --cache=true

.build-docker:
  extends: .build-docker-kaniko
  variables:
    DOCKERFILE_PATH: Dockerfile
    CONTEXT_PATH: ${CI_PROJECT_DIR}
    IMAGE_NAME: web_calculator
    IMAGE_TAG: 0.0.$CI_PIPELINE_IID

.postman api testing:
  stage: func_test
  image:
    name: postman/newman
    entrypoint: [""]
  extends: .docker-registry-auth
  services:
    - name: ${CI_REGISTRY_IMAGE}/web_calculator:0.0.$CI_PIPELINE_IID
      alias: web-app
  script:
    - npm install -g newman
    - npm update
    - newman run postman_collections/postman_collection.json --env-var "baseUrl=web-app:5000" -r cli,junit --reporter-junit-export ./newman/report.xml
    - cat ./newman/report.xml
  artifacts:
    paths:
      - ./newman
    expire_in: 1 week

.ssh-connection-from-docker:
    before_script:
        - apk add openssh-client bash
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - chmod 700 ~/.ssh


deploy-app:
  stage: deploy
  image: docker:24.0.7-dind-alpine3.18
  extends: .ssh-connection-from-docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create docker_lab --docker "host=ssh://ip172-18-0-86-cme10ltnp9tg00bor3ng@direct.labs.play-with-docker.com"
    - docker --context docker_lab run -d -p 80:80 ${CI_REGISTRY_IMAGE}/$IMAGE_NAME:$IMAGE_TAG