stages:
  - test
  - build
  - deploy


.pytest:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest --junitxml=junit.xml tests/unit_tests
  artifacts:
    reports:
      junit: junit.xml

.docker-registry-auth:
    before_script:
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

.build-docker-kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  extends: .docker-registry-auth
  script:
    - >-
      /kaniko/executor
      --context "${CONTEXT_PATH}"
      --dockerfile "${DOCKERFILE_PATH}"
      --cache-copy-layers
      --destination "${CI_REGISTRY_IMAGE}/$IMAGE_NAME:$IMAGE_TAG"
      --cache=true

.build-docker:
  extends: .build-docker-kaniko
  variables:
    DOCKERFILE_PATH: Dockerfile
    CONTEXT_PATH: ${CI_PROJECT_DIR}
    IMAGE_NAME: web_calculator
    IMAGE_TAG: 0.0.$CI_PIPELINE_IID
  
.ssh-connection-from-docker: 
    before_script:
        - apk add openssh-client bash
        - eval $(ssh-agent -s)
        - ssh-keygen -t ed25519
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

deploy-app:
  stage: deploy
  image: docker:24.0.7-dind-alpine3.18
  extends: .ssh-connection-from-docker 
  script: 
    - docker context create docker_lab --docker "host=ssh://ip172-18-0-45-clfje1csnmng00aumgh0@direct.labs.play-with-docker.com"
    - docker --context docker_lab run -d -p 80:80 nginx