name: bluegreen
version: "0.1"
services:
  blue:
    image: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}
    restart: on-failure
    depends_on:
      - nginx
    expose:
    - "5000"
    environment:
    - VIRTUAL_HOST=demo1.$PWD_URL
    - VIRTUAL_PORT=5000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000/health
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 25s


  green:
    image: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}
    restart: on-failure
    depends_on:
    - nginx
    expose:
    - "5000"
    environment:
    - VIRTUAL_HOST=demo1.$PWD_URL
    - VIRTUAL_PORT=5000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:0000/health
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 25s

  nginx:
    image: nginxproxy/nginx-proxy:latest
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
